## Acrylic主题配置文件
############################################################################################################
# 为避免主题更新后，配置文件被覆盖，请复制一份此文件到站点根目录下的_config.Acrylic.yml文件中，修改_config.Acrylic.yml文件中的配置
############################################################################################################
# 修改此文件前，请仔细阅读官方文档：https://next-docs.acrylic.org.cn/
############################################################################################################

# 站点设置
site:
  name: # 左上角显示内容
    class: i_class #i_class/text/img
    custom: fa-solid fa-ghost #自定义内容
  siteIcon: /img/favicon.png # 网页icon
  icon: /img/favicon.png # 页脚的icon、加载动画默认的icon
  icp: # ICP

# 导航栏
nav:
  #导航栏左侧
  left:
    enable: true
    menu:
      我的:
        博客:
          icon: /img/favicon.png
          url: /
  # 导航栏内容
  menu:
    文库:
      url: false
      child:
        文章列表:
          url: /archives/
          icon: fa-solid fa-box-archive
        全部分类:
          url: /categories/
          icon: fa-solid fa-cube
        全部标签:
          url: /tags/
          icon: fa-solid fa-tags
    # 专栏:
    #   url: false
    #   child:
    #     Android 开发日常:
    #       url: /tags/Android/
    #       icon: fa-solid fa-mobile
    我的:
      url: false
      child:
        我的装备:
          url: /equipment/
          icon: fa-solid fa-laptop
        关于我:
          url: /about/
          icon: fa-solid fa-user

  # 导航栏右侧快捷菜单
  right: # @todo 允许用户自定义
    travellings: false #开往
    random: true #
    console: false #控制台

# heo式顶部一大坨
hometop:
  bbtime: true

  banner:
    enable: true
    title: 代码人生<br>与科技生活
    url: GAVINLIU.CN
    icon:
      Android:
        img: /img/icon/Android.png
        color: "#ffffff"
      Apple:
        img: /img/icon/Apple.svg
        color: "#ffffff"
      Java:
        img: /img/icon/Java.png
        color: "#ffffff"
      Kotlin:
        img: /img/icon/Kotlin.png
        color: "#27282c"
      Python:
        img: /img/icon/Python.png
        color: "#ffffff"
      Swift:
        img: /img/icon/Swift.png
        color: "#eb6840"
      HTML:
        img: /img/icon/HTML.png
        color: "#e9572b"
      CSS3:
        img: /img/icon/CSS3.png
        color: "#2c51db"
      JS:
        img: /img/icon/JS.png
        color: "#f7cb4f"
      Docker:
        img: /img/icon/docker.png
        color: "#57b6e6"
      Git:
        img: /img/icon/git.png
        color: "#df5b40"
      Sketch:
        img: /img/icon/Sketch.png
        color: "#ffffff"
      AE:
        img: /img/icon/ae.png
        color: "#989bf8"
      PS:
        img: /img/icon/ps.png
        color: "#4082c3"

  categoryGroup:
    G1:
      name: 必看精选
      icon: fa-solid fa-star
      url: /tags/必看精选/
    G2:
      name: 代码人生
      icon: fa-solid fa-code
      url: /tags/代码人生/
    G3:
      name: 科技生活
      icon: fa-solid fa-microchip
      url: /tags/科技生活/

  recommendList:
    sup: 新品推荐
    title: Snapmod
    url: /2018/07/16/90a0e986eb9b.html
    img: /img/recommend_banner.png
    color: "#4a4a4a"

# 个人卡片
aside:
  home:
    noSticky: "about,flip"
    Sticky: "newestPost,allInfo"
  post:
    noSticky: "about"
    Sticky: "newestPost"
  page:
    noSticky: "about,flip"
    Sticky: "newestPost,allInfo"

  card:
    avatar: /img/avatar.png
    content: 这有关于<b>开发</b>、<b>技术</b>相关的问题和看法，还有关于<b>数码产品</b>相关的教程和测评。<br/><br/>相信你可以在这里找到对你有用的知识和教程。
    information:
      Github:
        icon: fa-brands fa-github
        url: https://github.com/gavinliu
      Mail:
        icon: fa-solid fa-envelope
        url: mailto:gavin6liu@gmail.com
    button:
      text: 更多信息
      url: /about

  flip:
    color: "#0099FF"
    face:
      title: QQ群
      desc: 加入官方QQ群与我们交流
    backface:
      title: 扫一扫
      desc: 获取最新信息和帮助
      img: /img/qqgroup.png

  toc:
    post: true
    page: false

  # 建站时间
  siteinfo:
    postcount: true
    wordcount: true
    pv: false
    uv: false
    updatetime: false
    runtimeenable: true
    runtime: "2012-02-28 00:00:00"

# 页脚
footer:
  information:
    left:
      # Github:
      #   icon: fa-brands fa-github
      #   url: https://github.com/gavinliu
      # Mail:
      #   icon: fa-solid fa-envelope
      #   url: mailto:gavin6liu@gmail.com
    right:
      # 网易云:
      #   icon: fa-solid fa-music
      #   url: /
      # bilibili:
      #   icon: fa-brands fa-youtube
      #   url: /

  group:
    # 导航:
    #   文章归档: /archives/
    #   文章分类: /categories/
    #   文章标签: /tags/
    #   友链: /link/
    # 服务:
    #   51la统计: https://51.la/
    #   百度统计: https://tongji.baidu.com/
    #   TianliCDN: https://ql.tianli0.top/
    # Acrylic:
    #   主题官网: https://acrylic.zhheo.com/
    #   Github: https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic
    #   Heo: https://blog.zhheo.com/
    # 推荐友链:
    #   Heo: https://blog.zhheo.com/
    #   Akilar: https://akilar.top

  randomlink: false

  cdn:
    url:
    desc:
  rss:
    url: /atom.xml
  license:
    url: https://creativecommons.org/licenses/by/4.0/
    icon: fas fa-closed-captioning

page:
  error: true
  tags: true
  categories: true
  default:
    cover: /img/cover/default.png

# 文章页默认设置
post:
  default:
    cover: /img/cover/default.png
    locate: 成都
    copyright: 原创
    excerpt: 100
  meta:
    date: true
    updated: false
    locate: true
    wordcount: true
    readtime: true
    pv: false
    comment: false
  award:
    enable: false
    wechat:
    alipay:
    url:
  covercolor: #文章cover取色
    enable: true
    local: true

# 关于界面
about: true

# 404页面
errorpage:
  img: /img/acrylic.png
  text: =awa= 页面走丢了
  recommendList: true

# 懒加载
lazyload:
  enable: false
  placeholder: /img/acrylic.png
  errorimg: /img/acrylic.png

# 图片灯箱
lightbox: true

#代码高亮增强
hightlight:
  enable: true
  hightlimit: 200

# 加载动画
loading:
  fullpage: false
  pace: true

# 第三方设置
thirdparty:
  wordcount: true

  busuanzi:
    enable: false
    usecomment: false #当评论系统开启时文章页面使用评论系统的统计数据

  search:
    algolia_search:
      enable: false
      # hits:
      #   per_page: 6
    local_search:
      enable: false
      preload: false
      CDN:

  aplayer:
    enable: false
    server: tencent
    id: 1708664797

  consolePlus: false

# 评论
comment:
  enable: false
  twikoo:
    envId:
    # region: ap-shanghai
    path: window.location.pathname

# 插入代码到头部 </head> 之前 和 底部 </body> 之前
# 插入额外代码 如：统计，广告等
extends:
  head:
    - <script charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js"></script>
    - <script>LA.init({id:"3FVRnNbwv2ZoRqcz",ck:"3FVRnNbwv2ZoRqcz"})</script>
  body:

# 非必要勿动
cdn:
  head:
    pacejs: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/pace/1.2.4/pace.min.js
    fontawesomecss: https://cdn.bootcdn.net/ajax/libs/font-awesome/6.3.0/css/all.min.css
    snackbarcss: /lib/snackbar.min.css
    qrcodejs: /lib/qrcode.min.js
    twikoojs: https://cdn.staticfile.org/twikoo/1.6.10/twikoo.all.min.js
    instantsearch: https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/instantsearch.js/4.39.0/instantsearch.production.min.js
    algolia: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/algoliasearch/4.12.1/algoliasearch-lite.umd.min.js
  body:
    swipercss: /lib/swiper.min.css
    pjaxjs: /lib/pjax.min.js
    lazyloadjs: /lib/lazyload.min.js
    snackbarjs: /lib/snackbar.min.js
    viewimagejs: /lib/view-image.min.js
    waterfalljs: /lib/waterfall.min.js
    swiperjs: /lib/swiper.min.js
    busuanzijs: https://npm.elemecdn.com/penndu@1.0.0/bsz.js
    aplayercss: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.css
    aplayerjs: https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.js
    metingjs: lib/meting.min.js
